Develop
lardc/hw-ECDCVoltageBoard pull request #1
Opened 2020-09-22 10:24 UTC by embedder71

ЭМ ECDCVoltageBoard. α-версия

2020-09-28 12:23 UTC, asytyi requested changes
Общий комментарий по коду.
Рекомендую прочитать книгу [Роберт Мартин - Чистый код](https://lardc.slack.com/archives/C0123HYSAAH/p1587385356004700?thread_ts=1587376887.004300&cid=C0123HYSAAH), чтобы мы могли общаться на одном языке. Является своего рода классикой, с автором можно соглашаться или не соглашаться (только если аргументированно), но мы нашли для себя большинство рекомендаций полезными.

Общие замечания, т.к. не везде по коду их отметил:
1. Пометки `// TODO` и закомментированный код в проекте оставлять не следует. Это замусоривает проект, требует дальнейшей чистки, тем более сейчас есть более совершенные инструменты для работы с будущими изменениями. В частности [Issues](https://github.com/lardc/hw-ECDCVoltageBoard/issues). Позволяет инициировать обсуждения, открывать, закрывать, сохраняя историю обсуждения и чистоту кода проекта.

2. Магических чисел (незадефайненных числовых констант) в коде быть не должно.

3. Следует пользоваться функцией автоформатирования кода. Файл лежит здесь:
`d:\proton\Documents\Software\Code style\LARDC.xml`
Как подключить написано [здесь](https://lardc.slack.com/archives/C0123HYSAAH/p1588523276002100?thread_ts=1587376887.004300&cid=C0123HYSAAH). Как пользоваться: Правый клик по файлу -> Source -> Format. Или аналогично по выделенному фрагменту кода, если что-то скриптом форматируется некорректно.

5. По комментариям к коммитам почитать [эту статью](https://habr.com/ru/post/416887/). Мы остановились на том, что достаточно к коммиту комментарий-резюме примерно на 50 символов. Это позволяет быстро отслеживать правки через Show Log или интерфейс Гитхаба. Писать перечень изменённых файлов — лишняя информация, которая содержится в теле самого коммита. Писать в комментарии код версии (альфа, бета и т.д.) — лишняя информация. Она есть в истории пул-реквестов и структуре веток.
![Плохо](https://user-images.githubusercontent.com/63667955/94431807-74256380-019e-11eb-8364-068daba4ba0d.png)
![Хорошо](https://user-images.githubusercontent.com/63667955/94431813-77b8ea80-019e-11eb-9378-48a18db62dec.png)

2020-09-28 12:23 UTC, asytyi commented on Firmware/Source/BCCIxParams.h
> +#define CAN_MASTER_NID_MPY			18				// �������� ������ Master	//TODO change? CAN_MASTER_NID_MPY
Комментарии TODO из кода необходимо убрать

2020-09-28 12:23 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +//TODO :debugging stage: set GPIO_SREG_OE1 H/L
Аналогично TODO

2020-09-28 12:23 UTC, asytyi commented on Firmware/Source/Controller/Diagnostic.c
> +			break;
Закомментированного кода не должно быть в проекте. Если в данные момент код не нужен, но есть опасения, что он понадобится в будущем, то восстановить старый код можно средствами git. Мёртвый код захламляет проект.

По комментариям надо придерживаться следующего подхода:
-  Постараться избежать необходимости комментария. Код должен быть самодокументируем. Вместо функции `ADC_Measure(ADC2,1);` использовать обёртку `MEASURE_Voltage()`. Это изолирует логику функции и позволит менять её не затрагивая верхний уровень и даст понимание назначения функции;
- Если без комментария не обойтись, то следует использовать надстрочные комментарии:
```
// Коментарий
DBGACT_TestWaveform();
```
 Комментарии в конце строки следует использовать только для однотипных монолитных блоков, и при этом соблюдать единообразие форматирования. Например как в [Constraints](https://github.com/lardc/hw-ECDCVoltageBoard/blob/develop/Firmware/Source/Platform/Constraints.c)

2020-09-28 12:23 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +//-----------------------------
Цифровых констант в коде быть не должно за очень редкими исключениями. Например, перебор в цикле бит в байте `for(i = 0; i < 8; i++)`.
В остальных случаях константы должны быть объявлены через `define` или `const` переменную, в зависимости от задачи.

Функции `DBGACT_RelayCtrlsOn()` и void `DBGACT_RelayCtrlsOff()` являются копиями друг друга, что увеличивает объём кода, вероятность ошибки и усложняет правки. Почему не сделать одну функцию `DBGACT_RelayCtrls(uint16_t Relay, bool State)` и не передавать в неё параметрами номер реле и тип действия? Если хочется, то сделать обёртку `DBGACT_RelayCtrlsOn(uint16_t Relay)`.

2020-09-28 12:23 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +//-----------------------------
Аналогично замечаниям функции `DBGACT_RelayCtrlsOn()`

2020-09-28 12:23 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +		case 1:
Аналогично замечаниям по константам

2020-09-28 12:23 UTC, asytyi commented on Firmware/Source/Controller/LowLevel.c
> +	LL_UpdateStateCtrls();
При написании кода надо придерживаться правил форматирования (пробелы между операторами, отступы и т.д.). По использованию автоформатирования напишу ниже.

2020-09-29 08:31 UTC, embedder71 commented on Firmware/Source/Controller/Controller.c
> +//TODO :debugging stage: set GPIO_SREG_OE1 H/L
Поправил.

2020-09-29 08:32 UTC, embedder71 commented on Firmware/Source/Controller/Diagnostic.c
> +			break;
Поправил.

2020-09-29 08:32 UTC, embedder71 commented on Firmware/Source/Controller/DebugActions.c
> +//-----------------------------
Поправил.

2020-09-29 08:32 UTC, embedder71 commented on Firmware/Source/Controller/DebugActions.c
> +//-----------------------------
Поправил.

2020-09-29 08:32 UTC, embedder71 commented on Firmware/Source/Controller/DebugActions.c
> +		case 1:
Поправил.

2020-09-29 08:33 UTC, embedder71 commented on Firmware/Source/Controller/LowLevel.c
> +	LL_UpdateStateCtrls();
Поправил.

2020-09-29 12:45 UTC, asytyi approved these changes
Принято!

2020-09-29 12:46 UTC, merged